#!/usr/bin/env node
/**
 * Resumable curation status. Prints progress and writes docs/curation-queue.md
 * so an agent (or a human) can see, at a glance, what's done and what's next.
 * State is derived entirely from the packs — a pack is "curated" once its
 * coverage is no longer 'mechanical'/'draft'. No separate state to sync.
 *
 * Run: node scripts/curation-status.mjs
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const packDir = join(root, 'rules', 'conditions');

const packs = readdirSync(packDir).filter(f => f.endsWith('.json') && !f.endsWith('.draft.json'))
    .map(f => JSON.parse(readFileSync(join(packDir, f), 'utf8')));

const curated = packs.filter(p => p.coverage !== 'mechanical' && p.coverage !== 'draft');
const todo = packs.filter(p => p.coverage === 'mechanical' || p.coverage === 'draft');
curated.sort((a, b) => a.conditionId.localeCompare(b.conditionId));
todo.sort((a, b) => a.conditionId.localeCompare(b.conditionId));

const pct = ((curated.length / packs.length) * 100).toFixed(1);
const todoRows = todo
    .map(p => `| ${p.conditionId} | ${p.name} | ${p.rules?.length ?? 0} | ${p.gaps?.length ?? 0} |`)
    .join('\n');

let md = `# Curation Queue

Progress: **${curated.length} / ${packs.length} curated (${pct}%)**, ${todo.length} to go.
Generated by \`node scripts/curation-status.mjs\`. Process: \`agents/rule-curation-agent.md\`.

A condition is **done** when its pack \`coverage\` is \`complete\` or \`partial\`
(verified vs the RCKMS Word doc). \`mechanical\` = auto-converted from legacy,
matches legacy ~99% but NOT yet verified. To continue: pick the next row in
"To curate", follow the agent loop, commit.

## Curated (${curated.length})

| ID | Condition | Coverage | Source doc |
|---|---|---|---|
${curated.map(p => `| ${p.conditionId} | ${p.name} | ${p.coverage} | ${p.source?.document || ''} |`).join('\n')}

## To curate (${todo.length}) — next up first

| ID | Condition | Rules | Gaps flagged |
|---|---|---|---|
${todoRows}
`;
md = md.replace(/\n{2,}$/, '\n');

writeFileSync(join(root, 'docs', 'curation-queue.md'), md);
console.log(`Curated ${curated.length}/${packs.length} (${pct}%). ${todo.length} remaining.`);
console.log(`Next up: ${todo.slice(0, 5).map(p => p.conditionId).join(', ')}${todo.length > 5 ? ' …' : ''}`);
console.log('Wrote docs/curation-queue.md');
